### ISSUE TITLE
Add Code of Conduct to Read me 

### ISSUE THREAD

**Issue by rohank2502** [rohank2502/DSA_in_Cpp#2]
Hey, This is good first !! Please let the New comers do this !!

In this issue you have to link the code of conduct file in read me 

1.Open Code-of-Conduct.md
2.Copy the path link 
3.Open Readme.md
4.On line 11 add the given code

`<h2><a href="path of codeofconduct.md">CODE OF CONDUCT</a></h2>`

5. Do name the commit properly and create a pull request linking to this issue.

**Comment by Abkt2001** [comment]
Can I contribute

**Comment by rohank2502** [comment]
> 
> 
> Can I contribute

For Sure !!

**Comment by rohank2502** [comment]
Start Working @Abkt2001  Deadline Till Today 7 pm Its  5 min Work so given Deadline !!

**Comment by rohank2502** [comment]
> 
> 
> Can I contribute

Do read the [Contribution_Guidelines.md](Contribution_Guidelines.md)
